runtime: java
runtime_config:
  jdk: openjdk8
service: default
env: flex
manual_scaling: 
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
beta_settings:
  enable_app_engine_apis: true

